name: IBM Cloud wzcxdgh Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 12 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        WZCXDGH_ACCOUNT: ${{ secrets.WZCXDGH_ACCOUNT }}
        WZCXDGH_NUM: ${{ secrets.WZCXDGH_NUM }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $WZCXDGH_ACCOUNT
        $WZCXDGH_NUM
        no
        EOF
    - name: Target IBM Cloud
      env:
        WZCXDGH_ID: ${{ secrets.WZCXDGH_ID }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -g "$WZCXDGH_ID"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install -v 6.51.0
    - name: Restart IBM Cloud
      env:
        WZCXDGH_APP_NAME: ${{ secrets.WZCXDGH_APP_NAME }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud cf restart "$WZCXDGH_APP_NAME"
